name: 'Sentry Artifacts'
description: 'Handles uploading coverage/test artifacts to codecov and zeus'
runs:
  using: "composite"
  steps:
    - name: Upload to codecov
      shell: bash
      run: |
        coverage_files=$(ls .artifacts/*coverage.xml || true)
        if [[ -n "$coverage_files" || -f .artifacts/coverage/cobertura-coverage.xml ]]; then
          pip install -U codecov
          codecov
        fi

    # Setup custom pytest matcher, see https://github.com/actions/setup-node/issues/97
    - name: Upload to zeus
      shell: bash
      env:
        PATH: "$(yarn global bin):$PATH"
      run: |
        yarn global add @zeus-ci/cli
        yarn zeus upload -t "text/xml+xunit" .artifacts/*junit.xml
        yarn zeus upload -t "text/xml+coverage" .artifacts/*coverage.xml
        yarn zeus upload -t "text/xml+coverage" .artifacts/coverage/cobertura-coverage.xml
        yarn zeus upload -t "text/html+pytest" .artifacts/*pytest.html
        yarn zeus upload -t "text/plain+pycodestyle" .artifacts/*pycodestyle.log
        yarn zeus upload -t "text/xml+checkstyle" .artifacts/*checkstyle.xml
        yarn zeus upload -t "application/webpack-stats+json" .artifacts/*webpack-stats.json
